"""Render project digests + lessons as a markdown file inside the target
repo (V2_PLAN 5.3).

This is the concrete mechanism for "memory layer over your coding life":
the digest and the project-scoped lessons BlipShell already maintains are
useless to every other tool while they live in a SQLite blob. Rendered as
`.blipshell/DIGEST.md` in the project root, Claude Code (or anything else
that reads the repo) inherits months of decisions and hard-won lessons for
free.

Deliberately WRITES the file and stops — committing is the user's call.
An assistant that commits into repos on its own schedule is the kind of
surprise that erodes exactly the trust this feature is meant to build.

The file carries a generated-by header with the source of truth named, so
a human finding it cold knows not to hand-edit (the next render overwrites).
"""

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

EXPORT_DIRNAME = ".blipshell"
EXPORT_FILENAME = "DIGEST.md"

_HEADER = """<!-- Generated by BlipShell from its memory store — do not hand-edit.
     Source of truth: project digest + lessons in data/blipshell.db.
     Regenerated on session close and by the nightly rebuild. -->
"""


def render_markdown(project_name: str, digest: Optional[str],
                    lessons: list, updated_at: Optional[str] = None) -> str:
    """The file body. Pure function — testable without a filesystem."""
    stamp = updated_at or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    parts = [
        _HEADER,
        f"# {project_name} — BlipShell project digest",
        f"_Updated {stamp}_",
        "",
    ]
    if digest:
        parts += ["## Digest", "", digest.strip(), ""]
    if lessons:
        parts += ["## Lessons learned here", ""]
        # Highest-importance first; the file is for READING, not archival.
        ranked = sorted(lessons, key=lambda l: l.importance, reverse=True)
        for lesson in ranked:
            parts.append(f"- {lesson.content.strip()}")
        parts.append("")
    if not digest and not lessons:
        parts += ["_No digest or lessons recorded yet._", ""]
    return "\n".join(parts)


async def export_digest(sqlite, project_name: str) -> Optional[Path]:
    """Write the project's digest file into its repo. Returns the path, or
    None when it can't (no root_path, root missing, nothing to write).

    Failure here must never break the caller — session close and nightly
    both continue if the export can't happen; it logs and returns None.
    """
    try:
        project = await sqlite.get_project(project_name)
        if not project:
            return None
        root = project.get("root_path")
        if not root or not Path(root).is_dir():
            logger.debug(
                "Digest export skipped for '%s': no usable root_path (%r)",
                project_name, root,
            )
            return None

        import json
        meta = json.loads(project.get("metadata_json") or "{}")
        digest = meta.get("digest")
        lessons = await sqlite.get_lessons_by_project(project_name)
        if not digest and not lessons:
            return None

        body = render_markdown(
            project_name, digest, lessons,
            updated_at=meta.get("digest_updated_at"),
        )

        out_dir = Path(root) / EXPORT_DIRNAME
        out_dir.mkdir(exist_ok=True)
        out_path = out_dir / EXPORT_FILENAME
        # Skip identical rewrites: touching the file dirties the repo and
        # noise-pings every file watcher for a no-op.
        if out_path.exists() and out_path.read_text(encoding="utf-8") == body:
            return out_path
        out_path.write_text(body, encoding="utf-8")
        logger.info("Exported digest for '%s' to %s", project_name, out_path)
        return out_path
    except Exception as e:
        logger.warning("Digest export failed for '%s': %s", project_name, e)
        return None
