"""Human-readable mirror of what the assistant believes. Export-only.

The ecosystem's most trusted memory systems won that trust with "your memory
is a folder you can read" (OpenClaw's USER.md/MEMORY.md, gptme's git-repo
agent — docs/FIELD_SURVEY_2026_09.md #3.8). BlipShell's SQLite store is
strictly more capable, but none of it is inspectable without the app. This
module writes the believed-state layers to Markdown files a person can open,
grep, and diff:

    data/mirror/USER_MODEL.md     the reasoned-conclusions document
    data/mirror/CORE_MEMORIES.md  curated identity facts, by category
    data/mirror/LESSONS.md        distilled lessons, importance-ordered
    data/mirror/SELF_THOUGHTS.md  the self-layer, with its gravity counters

Three deliberate limits, stated in every file header:

* **EXPORT-ONLY.** Hand-edits are NOT read back; the database is the truth
  and the nightly job regenerates these files. (Two-way sync is a real
  feature with real conflict semantics — if it ever ships, it ships with
  tests, not as a side effect of an exporter.)
* **Regenerated wholesale**, never appended, so the mirror can't drift from
  the store the way append-only docs drift.
* **It doubles as the portability layer**: these files are the thing you'd
  hand to another assistant (the field is converging on markdown memory
  formats — Hermes imports OpenClaw's; Letta serializes .af).

Files are UTF-8 (they're read by editors, not the cp1252 console).
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

MIRROR_DIR = "mirror"

_HEADER = (
    "<!-- Generated by BlipShell's nightly export_mirror job at {when}.\n"
    "     EXPORT-ONLY: hand-edits are NOT read back; the database is the\n"
    "     source of truth and this file is regenerated wholesale each run. -->\n"
)


def _header() -> str:
    return _HEADER.format(when=datetime.now(timezone.utc).isoformat(timespec="seconds"))


def _write(path: Path, title: str, body: str) -> None:
    path.write_text(f"{_header()}\n# {title}\n\n{body}\n", encoding="utf-8")


async def export_mirror(sqlite, db_path: str) -> dict:
    """Write the mirror files next to the database. Returns job stats."""
    out_dir = Path(db_path).parent / MIRROR_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    stats: dict[str, int | str] = {"dir": str(out_dir)}

    # User model — the document plus its revision stamp.
    doc = await sqlite.get_metadata("user_model")
    updated = await sqlite.get_metadata("user_model_updated_at")
    body = (doc or "(no user model yet)")
    if updated:
        body += f"\n\n*Last revised: {updated}*"
    _write(out_dir / "USER_MODEL.md", "User model (reasoned conclusions)", body)
    stats["user_model_lines"] = len((doc or "").splitlines())

    # Core memories, grouped by category, importance-ordered within.
    cores = await sqlite.get_active_core_memories()
    by_category: dict[str, list] = {}
    for c in cores:
        by_category.setdefault(c.category or "general", []).append(c)
    sections = []
    for category in sorted(by_category):
        lines = "\n".join(
            f"- ({c.importance:.2f}) {c.content}" for c in by_category[category]
        )
        sections.append(f"## {category}\n\n{lines}")
    _write(out_dir / "CORE_MEMORIES.md", "Core memories",
           "\n\n".join(sections) or "(none)")
    stats["core_memories"] = len(cores)

    # Lessons, importance-ordered. The number in front is rank/importance so a
    # reader can see WHY one outranks another, not just that it does.
    lessons = await sqlite.get_all_lessons()
    lessons.sort(key=lambda l: (l.importance, l.rank), reverse=True)
    lesson_lines = "\n".join(
        f"- (rank {l.rank}, imp {l.importance:.2f}"
        + (f", {l.project}" if getattr(l, "project", None) else "")
        + f") {l.summary or l.content}"
        for l in lessons
    )
    _write(out_dir / "LESSONS.md", "Lessons", lesson_lines or "(none)")
    stats["lessons"] = len(lessons)

    # Self-thoughts with the counters that make gravity legible.
    thoughts = await sqlite.get_self_thoughts(with_embeddings=False)
    thought_lines = "\n".join(
        f"- [{(t.get('created_at') or '?')[:10]}]"
        f" (w {t.get('weight', 1.0):.2f},"
        f" echoes {t.get('echo_count', 0)},"
        f" surfaced {t.get('surface_count', 0)}) {t['text']}"
        for t in thoughts
    )
    _write(out_dir / "SELF_THOUGHTS.md", "Lingering thoughts",
           thought_lines or "(none)")
    stats["self_thoughts"] = len(thoughts)

    logger.info("Memory mirror exported to %s", out_dir)
    return stats
